name: fancy_logger
description: The Logging Library for Flutter with SQLite Integration.
version: 0.1.2
repository: https://github.com/broxus/fancy_logger

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  archive: ^3.3.2
  collection: ^1.17.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  injectable: ^2.1.0
  logging: ^1.1.1
  path: ^1.8.2
  path_provider: ^2.0.12
  sqflite: ^2.2.6

dev_dependencies:
  broxus_flutter_analysis:
    git:
      url: https://github.com/broxus/flutter_templates.git
      ref: broxus_flutter_analysis-v1.0.0
  build_runner: ^2.4.5
  dart_code_metrics: ^5.6.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.3
  melos: ^3.1.0
  mocktail: ^0.3.0
  path_provider_platform_interface: ^2.0.6
  plugin_platform_interface: ^2.1.4
  sqflite_common_ffi: ^2.2.2
