name: Build and test package

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # runs the CI everyday at 6AM
    - cron: "0 6 * * *"

jobs:
  semantic_pull_request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build_and_test:
    uses: broxus/flutter_templates/.github/workflows/run-melos.yaml@main
    with:
      runner: macos-latest
