name: Create version PR

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version_parameters:
        description: 'Parameters to pass to "melos version"'
        required: true
        default: " "
        type: choice
        options:
          - "--"
          - "--prerelease"
          - "--graduate"

jobs:
  version_bump:
    uses: broxus/flutter_templates/.github/workflows/version.yaml@main
    with:
      version_parameters: ${{ inputs.version_parameters }}
    secrets:
      token: ${{ secrets.BOT_ACCESS_TOKEN }}
