name: Create version PR

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version_parameters:
        description: 'Parameters to pass to "melos version"'
        required: true
        default: " "
        type: choice
        options:
          - "--"
          - "--prerelease"
          - "--graduate"

jobs:
  version_bump:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}

    steps:
      # Setup
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }}
          fetch-depth: 0
      - name: Setup git
        run: |
          git config user.name "Odrin"
          git config user.email "odrin666@gmail.com"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.4'
          channel: 'stable'
          cache: true
          cache-key: flutter-:os:-:channel:-:version:-:arch:-:hash:-${{ hashFiles('**/pubspec.lock') }}
      - uses: bluefireteam/melos-action@v2

      - name: Bump version using melos
        run: melos version --all --yes ${{ inputs.version_parameters }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5.0.1
        with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }}
          commit-message: "chore: version bump"
          committer: Odin <odrin666@gmail.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: version-bump
          delete-branch: true
          title: "chore: version bump"
          body: |
            ## Description

            This is an automated PR to bump the version of the package.

            ## Type of Change

            - [x] 🗑️ Chore

          labels: |
            version_bump
            automated_pr
          draft: false